# Generated by Django 3.1.2 on 2020-10-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionSpectra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('wavelength', models.FloatField()),
                ('redshift', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FitsFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.CharField(max_length=256)),
                ('published_date', models.DateTimeField(verbose_name='date published')),
                ('config', models.TextField(null=True)),
                ('survey', models.CharField(max_length=200)),
                ('redshift', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='JsonFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.CharField(max_length=256)),
                ('published_date', models.DateTimeField(verbose_name='date published')),
                ('survey', models.CharField(max_length=200)),
                ('redshift', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TemplateSpectra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('redshift', models.FloatField()),
            ],
        ),
    ]
